Repository ywoo12321/KB_IT_Academy_4Team, pull requests merged in 2022-10, with the labels that each got.

#54 찜 목록 구현, 사용자 그래프 데이터 API 완료
  finalPJT/Server/accounts/views.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/mypage/__init__.py
  finalPJT/Server/mypage/admin.py
  finalPJT/Server/mypage/apps.py
  finalPJT/Server/mypage/migrations/__init__.py
  finalPJT/Server/mypage/models.py
  finalPJT/Server/mypage/tests.py
  finalPJT/Server/mypage/urls.py
  finalPJT/Server/mypage/views.py
  finalPJT/Server/server/settings.py
  finalPJT/Server/server/urls.py
  finalPJT/requirements.txt
Labels: 기능추가, 코드개선

#67 Swagger 적용, 이미지 반환 api 초안 작성
  finalPJT/Server/accounts/views.py
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/server/settings.py
  finalPJT/Server/server/urls.py
  finalPJT/Server/theme/agmon.jpg
  finalPJT/Server/theme/type.xlsx
  finalPJT/requirements.txt
Labels: 기능추가

#73 Feature/가은
  finalPJT/Server/lodgings/migrations/0002_alter_like_lodging_id_delete_lodging.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/theme/type.xlsx
Labels: 기능수정

#78 리팩토링, 랜덤 반환 api 초안
  finalPJT/Server/lodgings/migrations/0001_initial.py
  finalPJT/Server/lodgings/migrations/0002_alter_like_lodging_id_delete_lodging.py
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/mypage/views.py
Labels: 기능추가, 기능수정, 코드개선

#81 회원가입 선택 파일 api 수정(1)
  finalPJT/Server/lodgings/views.py
Labels: 기능수정

#88 추천 기능 리팩토링, 찜 추가, 삭제 초안
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/theme/type.xlsx
Labels: 기능추가, 기능수정, 코드개선

#91 Feature/가은
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/mypage/urls.py
  finalPJT/Server/theme/type.xlsx
Labels: 기능추가, 기능수정

#92 테스트 엑셀 정리, try catch수정, search 버그 수정
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/theme/type.xlsx
Labels: 버그수정, 기능수정, 코드개선

#95 like API 병합
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
Labels: 기능수정, 코드개선

#97 lodgings sub recommend 지역 개수 20개 미만 시 sample error issue 해결
  finalPJT/Server/lodgings/views.py
Labels: 버그수정

#101 detail page tag 영어>한글 변환, 코드 정리
  finalPJT/Server/lodgings/views.py
Labels: 기능수정, 코드개선

#102 병합 해결, 지역 추천 버그 수정
  finalPJT/Server/accounts/urls.py
  finalPJT/Server/accounts/views.py
  finalPJT/Server/lodgings/urls.py
  finalPJT/Server/lodgings/views.py
  finalPJT/Server/mypage/views.py
  finalPJT/Server/theme/type.xlsx
  finalPJT/requirements.txt
Labels: 버그수정, 기능수정
